version: "3.8"
services:
  http:
    build:
      context: ./docker/presentation-prod
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ./app:/project
      - ./data/presentation_logs:/var/log/apache2
    working_dir: /project
    ports:
      - "${HTTP_PORT}:80"
    restart: always
    environment:
      ENV: production
    links:
      - db
  db:
    env_file:
      - ./.env
    image: mysql:latest
    volumes:
      - ./docker/data/mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: "always"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10